/* 各関数におけるパラメータ型の変換用構造体 */
export const functionParams = {
  addNumbers: ['a','b'],
  getHostUpdated: [],
  getComsumedOp: [],
  getHostDataList: [],
  getAgencyInfo: ['gtfs_id'],
  getVersionId: ['gtfs_id', 'version_id'],
  getVersionInfo: ['gtfs_id', 'version_id'],
  getBusStops: ['gtfs_id', 'version_id'],
  getAgency: ['gtfs_id', 'version_id'],
  getCalendar: ['gtfs_id', 'version_id'],
  getCalendarDates: ['gtfs_id', 'version_id'],
  getFareAttributes: ['gtfs_id', 'version_id'],
  getFareRules: ['gtfs_id', 'version_id'],
  getFeedInfo: ['gtfs_id', 'version_id'],
  getOfficeJp: ['gtfs_id', 'version_id'],
  getRoutes: ['gtfs_id', 'version_id'],
  getShapes: ['gtfs_id', 'version_id'],
  getStopTimes: ['gtfs_id', 'version_id'],
  getTransfers: ['gtfs_id', 'version_id'],
  getTranslations: ['gtfs_id', 'version_id'],
  getTrips: ['gtfs_id', 'version_id'],
  getTimeTableByStopHash: ['gtfs_id', 'version_id', 'stop_hash'],
  getTimeTableByTripHash: ['gtfs_id', 'version_id', 'trip_hash'],
  getTimeTableByStopID: ['gtfs_id', 'version_id', 'stop_id'],
  getTimeTableByTripID: ['gtfs_id', 'version_id', 'trip_id'],
  getServiceIDs: ['gtfs_id', 'version_id', 'date'],
  findTrips: ['gtfs_id', 'version_id', 'stop_ids'],
  findTimeTableByStopID: ['gtfs_id', 'version_id', 'stop_id', 'date'],
  findTimeTableByTripIDs: ['gtfs_id', 'version_id', 'trip_ids'],
  fetchTimeTableV1: ['gtfs_id', 'options', 'version'],
  getStopsWithinRadius: ['lat', 'lon', 'radius'],
  getStopsBySubstring: ['substring'],
  getVehiclePositionFromURL: ['url'],
  getVehiclePositionUrls: [],
  getBusInfo: ['lat', 'lon'],
  getDataInfo: ['gtfs_id'],
  init: ['butter_root', 'config'],
  getBusRealTimeInfo: [],
  getStopsForBusPassingThrough: ['gtfs_id', 'stop_id', 'version_id'],
};

export const functionParamIsJSON = {
  addNumbers: [false,false],
  getHostUpdated: [],
  getComsumedOp: [],
  getHostDataList: [],
  getAgencyInfo: [false],
  getVersionId: [false, false],
  getVersionInfo: [false, false],
  getBusStops: [false, false],
  getAgency: [false, false],
  getCalendar: [false, false],
  getCalendarDates: [false, false],
  getFareAttributes: [false, false],
  getFareRules: [false, false],
  getFeedInfo: [false, false],
  getOfficeJp: [false, false],
  getRoutes: [false, false],
  getShapes: [false, false],
  getStopTimes: [false, false],
  getTransfers: [false, false],
  getTranslations: [false, false],
  getTrips: [false, false],
  getTimeTableByStopHash: [false, false, false],
  getTimeTableByTripHash: [false, false, false],
  getTimeTableByStopID: [false, false, false],
  getTimeTableByTripID: [false, false, false],
  getServiceIDs: [false, false, false],
  findTrips: [false, false, true],
  findTimeTableByStopID: [false, false, false, false],
  findTimeTableByTripIDs: [false, false, true],
  fetchTimeTableV1: [false, true, false],
  getStopsWithinRadius: [false, false, false],
  getStopsBySubstring: [false],
  getVehiclePositionFromURL: [false],
  getVehiclePositionUrls: [],
  getBusInfo: [false, false],
  getDataInfo: [false],
  init: [false, true],
  getBusRealTimeInfo: [],
  getStopsForBusPassingThrough: [false, false, false],
};