version: '3.8'
services:
  file-server:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run fileServer.go
    ports:
      - "8000:8000"
    restart: unless-stopped

  data-updater:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run dataUpdater.go
    restart: unless-stopped

  server-updater:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run serverUpdater.go
    restart: unless-stopped

#   caddy:
#     image: caddy:2
#     volumes:
#       - ./Caddyfile:/etc/caddy/Caddyfile
#       - caddy_data:/data
#       - caddy_config:/config
#     ports:
#       - "80:80"
#       - "443:443"
#     restart: unless-stopped
# volumes:
#   caddy_data:
#   caddy_config:
