version: '3.8'
services:
  file-server:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run fileServer.go
    ports:
      - "8000:8000"
    restart: unless-stopped
  file-server-v1:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run fileServer-v1.go
    ports:
      - "8001:8001"
    restart: unless-stopped

  data-updater:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run dataUpdater.go
    restart: unless-stopped
  data-updater-v1:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run dataUpdater-v1.go
    restart: unless-stopped

  # server-updater:
  #   image: golang:1.19
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: go run serverUpdater.go
  #   restart: unless-stopped

#  caddy:
#    image: caddy:2
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - ./caddy_data:/data
#      - ./caddy_config:/config
#    ports:
#      - "80:80"
#      - "443:443"
#    restart: unless-stopped
