version: '3.8'
services:
  file-server:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run fileServer.go
    ports:
      - "8000:8000"
    restart: unless-stopped

  data-updater:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run dataUpdater.go
    restart: unless-stopped

  server-updater:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run serverUpdater.go
    restart: unless-stopped

  # watchdog-timer:
  #   image: python:3.9-slim
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: python watchdog.py
  #   restart: unless-stopped

