version: "3.8"
services:
  0_rm:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run 0_rm.go
  1_scraping:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./:/app
  2_line2obj:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./:/app
    command: python 2_line2obj.py
  3_downloader:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./:/app
    command: python 3_downloader.py
  4_unziper:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./:/app
    command: python 4_unziper.py
  subdirectory_fix:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./:/app
    command: python subdirectory_fix.py
  5_split:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run 5_split.go
  6_add_gtfs_id_info:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run 6_add_gtfs_id_info.go
  7_add_datalist:
    image: golang:1.19
    volumes:
      - ./:/app
    working_dir: /app
    command: go run 7_add_datalist.go
  8_add_stopdata:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./:/app
    command: python 8_add_stopdata.py
