# Use the official Python image as base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install required packages
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run the script
CMD ["python", "./1_getDataList.py"]
